name: check

on:
  workflow_call:
    inputs:
      go-version-file:
        description: Path to go.mod
        type: string
        required: true
      cache-dependency-path:
        description: Path to go.sum
        type: string
        required: true
      golangci-lint-version:
        description: golangci-lint version
        type: string
        required: false

jobs:
  lint:
    if: inputs.golangci-lint-version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ inputs.golangci-lint-version }}
          args: --timeout=10m

  tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - run: go mod tidy
      - uses: int128/update-generated-files-action@v2

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
      - run: go fmt ./...
      - uses: int128/update-generated-files-action@v2
