name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      go-version-file: go.mod
      cache-dependency-path: go.sum
      golangci-lint-version: v1.61.0
